# Generated by Django 4.2.5 on 2023-10-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
    ]
