# Generated by Django 4.2.5 on 2023-10-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hi',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
