# Generated by Django 4.2.5 on 2023-10-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hi',
        ),
    ]
