# Generated by Django 4.2.7 on 2023-12-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0004_remove_like_post_remove_like_user_remove_post_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
    ]
